# Generated by Django 4.0.3 on 2022-05-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='m_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='m_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='タグ')),
            ],
        ),
        migrations.CreateModel(
            name='t_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('newadddate', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updatedate', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deletedate', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='閲覧数')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.m_category', verbose_name='カテゴリ')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='app.m_tag', verbose_name='タグ')),
            ],
            options={
                'ordering': ('-newadddate',),
            },
        ),
    ]
